apifetch/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("myapp.urls")),
]

myapp/urls.py
from django.urls import path, re_path
from . import views


app_name = "myapp"
urlpatterns = [
    path("api/", views.ArticalAPIView.as_view(), name="api"),
    path("", views.home, name="home"),
    path("create_user/", views.UserCreateView.as_view(), name="create_user"),
    path("create_activity/", views.ActivityCreateView.as_view(), name="create_activity"),
]

myapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class UserData(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    real_name = models.CharField(max_length=100)
    tz = models.CharField(max_length=100)
    def get_absolute_url(self):
        return reverse("myapp:api")
    def __str__(self):
        return str(self.id + " " + self.real_name)


class Activity(models.Model):
    user = models.ForeignKey(
        UserData, related_name="activity_periods", on_delete=models.CASCADE
    )
    start_time = models.CharField(max_length=100)
    end_time = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("myapp:api")

    def __str__(self):
        return str(self.user.real_name)

myapp/forms.py
from django import forms
from myapp.models import UserData, Activity


class UserForm(forms.ModelForm):
    class Meta:
        model = UserData
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["id"].label = "Unique Id"
        self.fields["real_name"].label = "Name"
        self.fields["tz"].label = "TimeZone"


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["user"].label = "User"
        self.fields["start_time"].label = "Start Time"
        self.fields["end_time"].label = "End Time"

myapp/views.py
import json
from django.shortcuts import render
from . import forms, models
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import UserSerializer
from django.views.generic import CreateView
from django.http import JsonResponse

def home(request):
    return render(request, "myapp/base.html", {})

class UserCreateView(CreateView):
    form_class = forms.UserForm
    model = models.UserData

class ActivityCreateView(CreateView):
    form_class = forms.ActivityForm
    model = models.Activity

class ArticalAPIView(APIView):
    def get(self, request):
        articles = models.UserData.objects.all()
        serializer = UserSerializer(articles, many=True)
        data_member = {"ok": "true", "members": serializer.data}
        data_member = json.dumps(data_member, indent = 4)
        json_object = json.loads(data_member)
        json_formatted_str = json.dumps(json_object, indent=4)
        return JsonResponse(json_object,safe=False)

templates/myapp/activity_form.html
<!DOCTYPE html>
{% extends "myapp/base.html" %}
{% load bootstrap3 %}
{% block body_block %}
<div class="container">

  <h2>Create Activity</h2>


      <form class="post-form"  method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <center><button type="submit" class="save btn btn-primary">ADD</button></center>

      </form>
</div>






{% endblock %}

templates/myapp/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>FULL THROTTLE LABS</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>
  <body style="background-color: #262626;">
    <!-- NAV BAR STARTS HERE -->

    <nav class="navbar navbar-expand-lg navbar-bg-dark fixed-top" style="background-color: #262626;">
        <a class="navbar-brand" href="{%url 'myapp:home' %}">Home</a>
        
    </nav>

          
        

    <!-- NAV BAR ENDS HERE -->


    <div class="container">
      <br>
      <br>
      <br>
      <ul class="list-group list-group-horizontal-lg">
            <li class="list-group-item list-group-item-dark"><a href="{% url 'myapp:create_user'%}">Create User</a></li>
            <li class="list-group-item list-group-item-dark"><a href="{% url 'myapp:create_activity'%}">Create Activity</a></li>
            <li class="list-group-item list-group-item-dark" ><a href="{% url 'myapp:api'%}">API fetch</a></li>
      </ul>
      <div style="margin-top:100px;">
      {% block body_block %}
        <ul >
          <li>
            <div style="color: white;">click on "Create User" to create new user</div>
          <li>
          <li>
            <div style="color: white;">click on "Creat Activity" to create new activity</div>
          <li>
          <li>
            <div style="color: white;">click on "API fetch" to get the data in JSON</div>
          <li>
        </ul>

        {% endblock %}


      </div>
    </div>


  </body>
</html>

templates/myapp/userdata_form.html
{% extends "myapp/base.html" %}
{% load bootstrap3 %}
{% block body_block %}
<div class="container">

  <h2>Create User</h2>


      <form class="post-form"  method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <center><button type="submit" class="save btn btn-primary text-center">ADD</button></center>s

      </form>
</div>






{% endblock %}